name: docs
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - libffi=3.4.4
  - openssl=3.0.12
  - pandoc=2.12
  - pip=23.3.1
  - python=3.11.5
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023d
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.41.2
  - xz=5.4.5
  - zlib=1.2.13
  - pip:
      - click==8.1.7
      - colorama==0.4.6
      - ghp-import==2.1.0
      - jinja2==3.1.2
      - markdown==3.5.1
      - markupsafe==2.1.3
      - mergedeep==1.3.4
      - mkdocs==1.5.3
      - packaging==23.2
      - pathspec==0.12.1
      - platformdirs==4.1.0
      - pymdown-extensions==10.7
      - python-dateutil==2.8.2
      - pyyaml==6.0.1
      - pyyaml-env-tag==0.1
      - six==1.16.0
      - watchdog==3.0.0
