site_name: CalSim 3 Documentation
nav:
  - Home: index.md
  - Hello CalSim: hellocalsim.md
  - Model Setup: modelsetup.md
  - Lookup Tables: lookuptables.md
theme: readthedocs
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences