site_name: CalSim 3 Documentation
nav:
  - Home: index.md
  - Hello CalSim: hellocalsim.md
  - Post-Processing: hellopostpro.md
  - Model Setup: modelsetup.md
  - Lookup Tables: lookuptables.md
  - Common CalSim 3 Variables: common_cs3vars.md
  - Common CalSim 2 Variables (Legacy): common_cs2vars.md
  - Glossary: glossary.md
  - FAQ: faq.md
  - CalSim Training: 
      - Training Overview: calsim-training/training-overview.md
      - Session 0 - Tech Setup: calsim-training/session0.md
      - Session 1 - Intro: calsim-training/session1.md
      - Session 2 - Upper Watersheds and Delta Hydrology: calsim-training/session2.md
      - Session 3 - Hydrology Part 1: calsim-training/session3.md
      - Session 4 - Modeling for Change and Access to Water: calsim-training/session4.md
      - Session 5 - Regulations and Operations I: calsim-training/session5.md
      - Session 6 - Regulations and Operations II: calsim-training/session6.md

theme: readthedocs
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
#extra_css:
#  - css/extra.css